### ISSUE TITLE
Request for pre-downloaded video links

### ISSUE THREAD

**Issue by lmsdss** [jianzongwu/MotionBooth#11]
Thank you for providing this amazing project! 

I encountered an issue while trying to download videos using the provided script `python -m scripts.download_dataset.panda70m`. Some videos require user authentication (e.g., age-restricted videos or private content).

Would it be possible to share pre-downloaded video links or provide an alternative dataset access method (e.g., direct links, Google Drive, or other storage platforms)? This would be immensely helpful for researchers working in environments where automated YouTube access is challenging.

Thank you for your support and this great resource!

**Comment by xuxuancheng0208** [comment]
Hi，how did you solve this problem？
