### ISSUE TITLE
Compatibility between 'xforemers' and 'torch'

### ISSUE THREAD

**Issue by Junoh-Kang** [jianzongwu/MotionBooth#3]
1. `pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121` requires pytorch 2.3.0 as in https://github.com/facebookresearch/xformers#installing-xformers. For me `pip install xformers==0.0.23.post1` works.
2. There are some typos 
- `pip intall -r requirements.txt` -> install
- first line of requirements should be 'matplotlib'

Thank you for sharing codes!

**Comment by jianzongwu** [comment]
Thanks for your suggestion! I have edited them into README.md

I'm glad to make it easier for people to use our repo.
