### ISSUE TITLE
Question about train code.

### ISSUE THREAD

**Issue by sieannHit** [jianzongwu/MotionBooth#7]
Hi jianzongwu! When I run the provided train demo:
### python -m scripts.train --config_path configs/lavie.yaml --obj_name dog3

A error is appeared: 
### ValueError: Cannot load <class 'src.models.unet_3d_condition_store_attn.LavieAttnStoreModel'> from checkpoints/lavie because the following keys are missing: up_blocks.3.attentions.2.transformer_blocks.0.attn_temp.to_out.0.bias, up_blocks.3.attentions.0.transformer_blocks.0.attn_temp.to_q.weight, up_blocks.2.attentions.0.transformer_blocks.0.norm_temp.bias, down_blocks.2.attentions.0.transformer_blocks.0.attn_temp.to_q.weight, ........

However. The inference code based on lavie model is runnable. May you help me to solve this question? Thank you in advance.

**Comment by jianzongwu** [comment]
Hi, Please update your codebase to the latest, and check carefully the LaVie checkpoint converting process in README.md.

There are several steps to convert the LaVie checkpoint to the diffusers format before we can train on it.

Please let me know if you have other questions!

**Comment by rosyForever** [comment]
I have the same issue, and I have already converted the LaVie checkpoint to the Diffusers format.

**Comment by jianzongwu** [comment]
> I have the same issue, and I have already converted the LaVie checkpoint to the Diffusers format.

Hello! Can you post the error message?
