### ISSUE TITLE
How to generate 1024 576 resolution video? I tested and found that 80G video memory is not enough

### ISSUE THREAD

**Issue by mrlihellohorld** [jianzongwu/MotionBooth#8]
How to generate 1024 576 resolution video? I tested and found that 80G video memory is not enough

**Comment by jianzongwu** [comment]
In our paper, we use the LaVie and ZeroScope model as foundation T2V models.
In default, LaVie model generates 320x512 videos, and ZeroScope generates 320x576 videos.
If you want to generate 1024x576 videos, maybe you can use ZeroScopeXL to extend the 320x576 video.

Remember to cast all the models to fp16 to reduce the memory usage.
Maybe you also need to enable xformers to further reduce the memory usage.
I believe a 80G memory is enough for generate a 1024x576 video, one in a batch.
